### ISSUE TITLE
XPC Services

### ISSUE THREAD

**Issue by steven-joruk** [dfrankland/xpc-connection-rs#12]
Hello!

Would you be interested in PRs to enable this crate to also cover creating XPC services?

I've started working on it separately, but the work you've already done will make up the majority of the functionality.

Cheers :).

**Comment by dfrankland** [comment]
I am totally down for it! Would you like me to add you as a collaborator?

**Comment by steven-joruk** [comment]
Sure, I'd be happy to help, thanks.
