### ISSUE TITLE
API discussion

### ISSUE THREAD

**Issue by steven-joruk** [dfrankland/xpc-connection-rs#15]
The API allows a kind of misuse:
```rust
let mut con = XpcConnection::new("com.apple.blued\0");
let a = con.connect();
let b = con.connect();
```

I think (but haven't verified) `a.connection` will remain open and its event handler will continue to be called, but its stream will be closed when `con.connect` is called again, so it's in an unusable state.

What do you think about modifying the API to:
1. Merge new with connect to force a 1 to 1 relationship between XpcConnection and a connection
1. Return a Result to cover the conversion of &str to a CString
1. Remove the need for the user to pass the terminating `\0`
1. Add a way for the user to control the dispatch queue, with consideration of the dispatch crate's Queue type
1. Add a way for the user to indicate whether they want the `XPC_CONNECTION_MACH_SERVICE_PRIVILEGED` set.

**Comment by dfrankland** [comment]
These all sound like good things 👍

**Comment by steven-joruk** [comment]
I'll create new issues for these.
